namespace Models.Models
{
    public partial class SeatManagement
    {
        public long Id { get; set; }
        public byte SeatNumber { get; set; }
        public int RemainingSeat { get; set; }
        public string? BookingReferenceCode { get; set; }
        public string? MainBookerReferenceCode { get; set; }
        public string? RescheduleReferenceCode { get; set; }
        public string? RerouteReferenceCode { get; set; }
        public string? PhoneNumber { get; set; }
        public string? NextOfKinName { get; set; }
        public decimal? Amount { get; set; }
        public decimal? PartCash { get; set; }
        public decimal? RerouteFeeDiff { get; set; }
        public decimal? UpgradeDowngradeDiff { get; set; }
        public decimal Discount { get; set; }
        public string? NextOfKinPhoneNumber { get; set; }
        public string? PickupPointImage { get; set; }
        public string? ReschedulePayStackResponse { get; set; }
        public string? CreatedBy { get; set; }
        public string? LuggageType { get; set; }
        public bool Rated { get; set; }
        public string? FullName { get; set; }
        public int Gender { get; set; }
        public int PassengerType { get; set; }
        public int PaymentMethod { get; set; }
        public int BookingStatus { get; set; }
        public int PickupStatus { get; set; }
        public int BookingType { get; set; }
        public int TravelStatus { get; set; }
        public int UpgradeType { get; set; }
        public int RescheduleStatus { get; set; }
        public int RescheduleMode { get; set; }
        public int RerouteStatus { get; set; }
        public int RerouteMode { get; set; }
        public int RescheduleType { get; set; }
        public DateTime? RescheduleDate { get; set; }
        public bool IsPrinted { get; set; }
        public bool IsRescheduled { get; set; }
        public bool IsRerouted { get; set; }
        public bool IsUpgradeDowngrade { get; set; }
        public bool IsMainBooker { get; set; }
        public bool HasReturn { get; set; }
        public bool IsReturn { get; set; }
        public bool FromTransload { get; set; }
        public int? RouteId { get; set; }
        public bool IsSub { get; set; }
        public bool IsSubReturn { get; set; }
        public string? OnlineSubRouteName { get; set; }
        public int? PickUpPointId { get; set; }
        public int? NoOfTicket { get; set; }
        public int? SubRouteId { get; set; }
        public Guid? VehicleTripRegistrationId { get; set; }
        public int? VehicleModelId { get; set; }
        public long? BookingId { get; set; }
        public int? BookingId1 { get; set; }
        public bool HasCoupon { get; set; }
        public string? CouponCode { get; set; }
        public DateTime CreationTime { get; set; }
        public long? CreatorUserId { get; set; }
        public long? DeleterUserId { get; set; }
        public DateTime? DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? LastModificationTime { get; set; }
        public long? LastModifierUserId { get; set; }
        public string? Posreference { get; set; }
        public DateTime? ExpiredDate { get; set; }
        public bool IsGhanaRoute { get; set; }
        public DateTime? IssuedDate { get; set; }
        public string? PassportId { get; set; }
        public string? PassportType { get; set; }
        public string? PlaceOfIssue { get; set; }
        public string? Nationality { get; set; }
        public decimal? Vat { get; set; }
        public string? Address { get; set; }
        public string? ChildNames { get; set; }
        public DateTime? DateOfBirth { get; set; }
    }
}
